[package]
name = "move_first_line"
version = "1.0.0"
authors = ["Kevin Moonen <dragonrider7225@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
